name: Pull request

on:
  pull_request:
    branches:
      - staging
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read
  pull-requests: write

env:
  GO_VERSION: "1.24.5"
  GO_PACKAGE_NAME: "github.com/smartertravel/awd2"
  GO_WORKING_DIRECTORY: "golang"
  GO_COVERAGE_THRESHOLD: 0 # TODO: Update this in PLUTO-561
  WEB_PATH: ${{ github.workspace }}/web
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MESSAGING_MOCK_KAFKA: true
  E2E_MODE: "true"
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtpKhUkmJnvHjKY3uEJHj
    Nf5G0O0V/jZ6eF/KoXT/QANhzVwWrwErBUBbRCABj+uAZYgiPY7RohUkk6vHaHo1
    N+hMUjSWuSBpck70FzP0yPkNquNwc1EE/0dRMXcElR93SNCfIky5f2TMwQGcNsbu
    cOQd0CbsDBetc4taZSGPv/lfyekYMXR/LNhlz81XTMQHgcX3dQNM5SWDLGlye1Va
    UX3zows7ZJ5wxD16O/aJRuDjYjzj0zw1v9yTemIDUXYcv56zZWnQEzsDcY35suZ7
    Yshsaw3VjYXC3IYPZDRgRwgf/V+oUmNknQ+7OvbYGEwoOVXKF907pAcXCMcNwZjd
    xwIDAQAB
    -----END PUBLIC KEY-----
  REDIS_MOCK: true

jobs:
  filter:
    name: 🔍 Filter changes
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      golang: ${{ steps.filter.outputs.golang }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            web:
              - 'web/**'
            golang:
              - 'golang/**'

  go-check:
    name: Go Lint
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.golang == 'true'
    steps:
      - name: Print Check
        run: echo "golang PR check run"

  typescript-check:
    name: Typescript Unit Test
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.web == 'true'
    steps:
      - name: Print Check
        run: echo "typescript PR check run"
