# DEPRECATED: This workflow has been replaced by separate staging.yml and main.yml workflows
# 
# New workflow structure:
# - staging.yml: Handles staging branch pushes, creates "Merge to main" PRs, deploys to staging
# - main.yml: Handles main branch pushes, creates releases, deploys to production, merges back to staging
# 
# This file is kept for reference but should not be used.

name: Release Please (DEPRECATED)

on:
  # This workflow is disabled - remove the 'workflow_dispatch' trigger to prevent accidental runs
  workflow_dispatch:
    inputs:
      confirm_deprecated:
        description: 'This workflow is deprecated. Use staging.yml and main.yml instead.'
        required: true
        type: boolean
        default: false

permissions:
  packages: read
  contents: write
  pull-requests: write
  id-token: write

jobs:
  deprecated-notice:
    runs-on: ubuntu-latest
    if: inputs.confirm_deprecated == true
    steps:
      - name: Deprecation Notice
        run: |
          echo "⚠️ WARNING: This workflow is DEPRECATED"
          echo ""
          echo "Please use the new workflow structure:"
          echo "- staging.yml: Handles staging branch pushes"
          echo "- main.yml: Handles main branch pushes and releases"
          echo ""
          echo "The new workflows provide:"
          echo "✅ Proper staging → main → production flow"
          echo "✅ Component-aware deployments"
          echo "✅ Automatic merge-back to staging"
          echo "✅ Better separation of concerns"
          echo ""
          echo "This workflow will be removed in a future update."
