name: Release Please

on:
  push:
    branches:
      - main

permissions:
  packages: read
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      web-v2--release_created: ${{ steps.release.outputs.web--release_created }}
      web-v2--tag_name: ${{ steps.release.outputs.web--tag_name }}
      golang-webhook--release_created: ${{ steps.release.outputs['golang/webhook--release_created'] }}
      golang-webhook--tag_name: ${{ steps.release.outputs['golang/webhook--tag_name'] }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: "${{ secrets.GH_BOT_V2_APP_ID }}"
          private-key: "${{ secrets.GH_BOT_V2_PRIVATE_KEY }}"
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
          target-branch: main
      - name: Print information
        run: |
          echo "Web release created: ${{ steps.release.outputs.web--release_created }}"
          echo "Web tag name: ${{ steps.release.outputs.web--tag_name }}"
          echo "Webhook release created: ${{ steps.release.outputs['golang/webhook--release_created'] }}"
          echo "Webhook tag name: ${{ steps.release.outputs['golang/webhook--tag_name'] }}"
          echo "Releases created: ${{ steps.release.outputs.releases_created }}"

  merge-back-to-staging:
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Setup GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: "${{ secrets.GH_BOT_V2_APP_ID }}"
          private-key: "${{ secrets.GH_BOT_V2_PRIVATE_KEY }}"
      - name: Authenticate GitHub CLI
        run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token
      - name: Merge main back to staging
        run: |
          gh api repos/${{ github.repository }}/merges \
            --method POST \
            --field base=staging \
            --field head=main \
            --field commit_message="Merge main back to staging after release"

  deploy-web:
    name: Deploy web
    needs: release-please
    if: needs.release-please.outputs.web-v2--release_created == 'true'
    uses: ./.github/workflows/release.yml
    with:
      component: web-v2
      override-tag: ${{ needs.release-please.outputs.web-v2--tag_name }}
      environment: production
    secrets: inherit

  deploy-webhook:
    name: Deploy webhook
    needs: release-please
    if: needs.release-please.outputs.golang-webhook--release_created == 'true'
    uses: ./.github/workflows/release.yml
    with:
      component: webhook
      override-tag: ${{ needs.release-please.outputs.golang-webhook--tag_name }}
      environment: production
    secrets: inherit
