name: Staging Workflow

on:
  push:
    branches:
      - staging

permissions:
  packages: read
  contents: write
  pull-requests: write
  id-token: write

jobs:
  extract-release-info:
    runs-on: ubuntu-latest
    outputs:
      release-info: ${{ steps.extract.outputs.release-info }}
      web-changed: ${{ steps.extract.outputs.web-changed }}
      webhook-changed: ${{ steps.extract.outputs.webhook-changed }}
      has-changes: ${{ steps.extract.outputs.has-changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install release-please CLI
        run: npm install -g release-please

      - name: Extract release information using dry-run
        id: extract
        run: |
          # Use release-please in dry-run mode to extract what would be released
          echo "Extracting release information..."

          # Run release-please in dry-run mode
          release_output=$(release-please release-pr \
            --token="${{ secrets.GITHUB_TOKEN }}" \
            --repo-url="${{ github.repository }}" \
            --target-branch=staging \
            --config-file=.github/release-please/config.json \
            --manifest-file=.github/release-please/manifest.json \
            --dry-run \
            --debug 2>&1 || true)

          echo "Release-please output:"
          echo "$release_output"

          # Check if there are any changes to release
          # Look for indicators that release-please would create releases
          if echo "$release_output" | grep -q "Would open [1-9]" || echo "$release_output" | grep -q "updating from.*to"; then
            echo "has-changes=true" >> $GITHUB_OUTPUT
            
            # Extract component information
            web_changed="false"
            webhook_changed="false"
            
            # Check for web component changes (look for web path or demo-typescript-app)
            if echo "$release_output" | grep -q "web/" || echo "$release_output" | grep -q "demo-typescript-app"; then
              web_changed="true"
            fi
            
            # Check for webhook component changes (look for golang/webhook path)
            if echo "$release_output" | grep -q "golang/webhook"; then
              webhook_changed="true"
            fi
            
            echo "web-changed=$web_changed" >> $GITHUB_OUTPUT
            echo "webhook-changed=$webhook_changed" >> $GITHUB_OUTPUT
            
            # Extract actual release information from dry-run output
            # Look for the release notes section in the output
            release_info=$(echo "$release_output" | awk '
              /^body:/ {found=1; sub(/^body:[[:space:]]*/, ""); print; next}
              /^updates/ || /^❯/ {found=0}
              found
            ')  
            # Use GitHub Actions multiline output format
            {
              echo 'release-info<<EOF'
              echo "$release_info"
              echo 'EOF'
            } >> $GITHUB_OUTPUT
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "web-changed=false" >> $GITHUB_OUTPUT
            echo "webhook-changed=false" >> $GITHUB_OUTPUT
            echo "release-info=No changes detected for release" >> $GITHUB_OUTPUT
          fi

  determine-deployment:
    runs-on: ubuntu-latest
    outputs:
      web--release_created: ${{ steps.release.outputs.web--release_created }}
      web--tag_name: ${{ steps.release.outputs.web--tag_name }}
      webhook--release_created: ${{ steps.release.outputs.webhook--release_created }}
      webhook--tag_name: ${{ steps.release.outputs.webhook--tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Setup GitHub App token
      #   id: app-token
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app-id: "${{ secrets.GH_BOT_V2_APP_ID }}"
      #     private-key: "${{ secrets.GH_BOT_V2_PRIVATE_KEY }}"
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: "${{ secrets.TOKEN }}"
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
          target-branch: main
          skip-github-pull-request: true
          skip-github-release: true
      - name: Debug Output
        run: |
          echo "Release output: ${{ toJson(steps.release.outputs) }}"

  upsert-merge-to-main-pr:
    needs: extract-release-info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Reset staging branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
      - name: Create/Update Merge to Main PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.TOKEN }}
          branch: merge-staging-to-main
          title: "🚀 Merge staging to main"
          body: ${{ needs.extract-release-info.outputs.release-info }}
          labels: automated

  deploy-web-to-staging:
    needs: determine-deployment
    if: needs.determine-deployment.outputs.web--release_created == 'true'
    uses: ./.github/workflows/release.yml
    with:
      component: web-v2
      environment: staging
      publish: true
      deploy: true

  deploy-webhook-to-staging:
    needs: determine-deployment
    if: needs.determine-deployment.outputs.webhook--release_created == 'true'
    uses: ./.github/workflows/release.yml
    with:
      component: webhook
      environment: staging
      publish: true
      deploy: true

  notify-completion:
    needs:
      [
        extract-release-info,
        determine-deployment,
        upsert-merge-to-main-pr,
        deploy-web-to-staging,
        deploy-webhook-to-staging,
      ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify workflow completion
        run: |
          echo "## Staging Workflow Completed"
          echo "- Changes detected: ${{ needs.extract-release-info.outputs.has-changes }}"
          echo "- Web component changed: ${{ needs.extract-release-info.outputs.web-changed }}"
          echo "- Webhook component changed: ${{ needs.extract-release-info.outputs.webhook-changed }}"

          if [ "${{ needs.extract-release-info.outputs.has-changes }}" = "true" ]; then
            echo "✅ Merge to main PR created/updated"
            echo "✅ Staging deployment initiated for changed components"
          else
            echo "ℹ️ No changes detected, no action taken"
          fi
